"""
walter — LLM-assisted dataset construction for LASA drugs.
"Walter, are these two LASA drugs? Make no mistakes."

All parameters, paths, and column names are in config.py — the single
source of truth. Edit there, not here.

R_clean: the active raw registry (_data/R_{ph|us}.csv), cleaned and
deduplicated. In-memory only, not saved to disk. Serves as the
sampling pool U is drawn from.

P: confirmed LASA pairs — either read from _data/P.csv (FROM_FILE=True)
or generated by the local LLM proposer (FROM_FILE=False). label=1.

U: similarity-filtered unlabeled pairs, sampled per-cluster from
R_clean via two-tier sampling (src/noise.py) so the emitted name graph
stays a union of disjoint components. label=0, not confirmed negative.

D = P ∪ U, deduplicated, with IPA transcriptions added. Saved as:
    _results/D.csv      classification — x_1, t_1, x_2, t_2, label
    _results/D_rank.csv same rows + group id, for a downstream
                         grouped/ranking split (see src/clustering.py)

Usage:
    python walter.py
"""

from numpy import source
import pandas as pd
from pandas import DataFrame

from config import (
    CLASS_RATIO,
    DataSource,
    DATA_SOURCE,
    FROM_FILE,
    P,
    D_OUT_CSV,
    SEED,
    TIER_2_SAMPLE_SIZE,
)

from src.dataset import assemble_and_save
import src.noise as noise
import src.preprocessing as pre
from pathlib import Path

def _load_positive_pairs(R_clean: pd.DataFrame, source: DataSource) -> pd.DataFrame:
    if FROM_FILE:
        P_file: Path = P[source]
        if not P_file.exists():
            raise FileNotFoundError(
                f"{P_file} not found. "
                "Place your confirmed LASA pairs CSV there, "
                "or set FROM_FILE = False in config.py to use the LLM proposer."
            )
        P_ = pd.read_csv(P_file)
        print(f"\nLoaded P from {P_file}: {len(P):,} pairs")
        return P_

    from config import LLM_OUTPUT_JSON
    from src.proposer.inference import load_inference, run_inference
    from src.proposer.llm import LocalModel

    run_inference(registry_df=R_clean, model_choice=LocalModel.QWEN3_1_7B)
    P_llm = load_inference(LLM_OUTPUT_JSON)
    print(f"\nGenerated P via LLM: {len(P_llm):,} pairs")
    return P_llm


def main() -> None:
    print(f"Data source    : {DATA_SOURCE.name}")
    print(f"U/P ratio      : 1:{CLASS_RATIO}")
    print(f"Tier 2 sample  : {TIER_2_SAMPLE_SIZE:,}")
    print(f"Seed           : {SEED}")
    print()
    print(f"Output: D → {D_OUT_CSV}")

    # --- Preprocessing ---
    R_clean: DataFrame = pre.run(source=DATA_SOURCE)
    print(f"\nCleaned registry: {len(R_clean):,} drug names")
    print(R_clean.head(10))

    # --- Confirmed LASA pairs (P) ---
    P_load: pd.DataFrame = _load_positive_pairs(R_clean, source=DATA_SOURCE)
    print(P_load.head())
    print("Columns:", list(P_load.columns))

    # --- Unlabeled pairs (U) ---
    U = noise.make_noise(
        pairs_df=P_load,
        registry_df=R_clean,
        ratio=CLASS_RATIO,
        tier_2_sample_size=TIER_2_SAMPLE_SIZE,
        seed=SEED,
    )
    print(U.head())

    # --- Assemble and save ---
    D = assemble_and_save(P_load, U, add_phonemes=True)
    print(D.head(10))
    print(f"\nD shape: {D.shape}")
    print(D["label"].value_counts().to_string())


if __name__ == "__main__":
    main()
