algorithm = "visual_weighted"
case_insensitive = false
separate = false

[costs]
same = 1.0
diff = 2.0

[group]
A = []
B = [1]
C = [2]
D = [1]
E = [0]
F = [0]
G = [2]
H = []
I = [3]
J = []
K = [4]
L = [3]
M = [5]
N = []
O = [6]
P = [7]
Q = [6]
R = [7]
S = []
T = [3]
U = [8]
V = [8]
W = [5]
X = [4]
Y = []
Z = []

a = []
b = [100]
c = []
d = [100]
e = []
f = [101]
g = [102]
h = [103]
i = [104]
j = [104]
k = [105]
l = [104]
m = [103]
n = [103]
o = []
p = [102]
q = [102]
r = []
s = []
t = [101]
u = []
v = [106]
w = [106]
x = [105]
y = [106]
z = []
