"""Central configuration for the Walter pipeline.

This folder holds all settings, file paths, column names, and model parameters.
Settings are organized by category:
    - paths:     where files, models, and outputs are stored.
    - schema:    standard column names and labels used in datasets.
    - sampling:  how non-confusable drug pairs (U) are sampled.
    - proposer:  settings for finding confusable drug pairs with AI.
    - phonetics: settings for speech pronunciation and similarity scoring tools.

All values are re-exported here so you can import them directly from `config`.
"""

from .paths import (
    ALIASES,
    D_CSV,
    D_FILENAME,
    D_PHO_CSV,
    D_PHO_FILENAME,
    DATA_DIR,
    DATA_SOURCE,
    DataSource,
    MODELS_DIR,
    N,
    P,
    R,
    R_CLEAN,
    RESULTS_DIR,
    U_CSV,
    U_FILENAME,
    USE_PRECLEANED_REGISTRY,
)
from .phonetics import (
    FIL_G2P_BATCH_SIZE,
    FIL_G2P_BIN,
    FIL_G2P_MODEL,
    IPA_BATCH_SIZE,
    PHOC_BIN,
    PHOC_CONFIG_DIR,
    PHONETIC_ALGORITHMS,
    TBB_BIN,
)
from .proposer import (
    DEEPSEEK_API_KEY,
    DEEPSEEK_MODEL,
    FROM_FILE,
    LASA_RUN_JSON,
    LASA_RUN_U_CSV,
    LLM_N_PROPOSALS,
    LLM_OUTPUT_FILENAME,
    LLM_OUTPUT_JSON,
    SOFT_LABELS,
    USE_API_MODEL,
)
from .sampling import (
    CANDIDATE_MIN_POOL,
    CANDIDATE_OVERSAMPLE_FACTOR,
    POSITIVE_PREVALENCE,
    SEED,
    SHUFFLE_SEED,
    SIMILARITY_THRESHOLD,
    TIER_1_PROPORTION,
    TIER_2_MAX_POOL_PER_CLUSTER,
    TIER_2_PROPORTION,
    TIER_2_SAMPLE_SIZE,
)
from .schema import (
    COL_LABEL,
    COL_T_ENG_1,
    COL_T_ENG_2,
    COL_T_FIL_1,
    COL_T_FIL_2,
    COL_T1,
    COL_T2,
    COL_X1,
    COL_X2,
    NEGATIVE_LABEL,
    P_INPUT_COLS,
    POSITIVE_LABEL,
    REGISTRY_COL,
    TRANSCRIPTION_LANGS,
    UNLABELED_LABEL,
)

__all__ = [
    "DataSource",
    "DATA_SOURCE",
    "DATA_DIR",
    "RESULTS_DIR",
    "MODELS_DIR",
    "R",
    "R_CLEAN",
    "USE_PRECLEANED_REGISTRY",
    "P",
    "N",
    "ALIASES",
    "U_CSV",
    "D_CSV",
    "D_PHO_CSV",
    "U_FILENAME",
    "D_FILENAME",
    "D_PHO_FILENAME",
    "REGISTRY_COL",
    "COL_X1",
    "COL_X2",
    "COL_T1",
    "COL_T2",
    "COL_T_ENG_1",
    "COL_T_ENG_2",
    "COL_T_FIL_1",
    "COL_T_FIL_2",
    "TRANSCRIPTION_LANGS",
    "COL_LABEL",
    "P_INPUT_COLS",
    "POSITIVE_LABEL",
    "UNLABELED_LABEL",
    "NEGATIVE_LABEL",
    "POSITIVE_PREVALENCE",
    "TIER_1_PROPORTION",
    "TIER_2_PROPORTION",
    "TIER_2_SAMPLE_SIZE",
    "TIER_2_MAX_POOL_PER_CLUSTER",
    "CANDIDATE_OVERSAMPLE_FACTOR",
    "CANDIDATE_MIN_POOL",
    "SIMILARITY_THRESHOLD",
    "SEED",
    "SHUFFLE_SEED",
    "FROM_FILE",
    "SOFT_LABELS",
    "LLM_N_PROPOSALS",
    "LLM_OUTPUT_JSON",
    "LLM_OUTPUT_FILENAME",
    "LASA_RUN_JSON",
    "LASA_RUN_U_CSV",
    "USE_API_MODEL",
    "DEEPSEEK_MODEL",
    "DEEPSEEK_API_KEY",
    "PHOC_BIN",
    "PHOC_CONFIG_DIR",
    "PHONETIC_ALGORITHMS",
    "TBB_BIN",
    "IPA_BATCH_SIZE",
    "FIL_G2P_BIN",
    "FIL_G2P_MODEL",
    "FIL_G2P_BATCH_SIZE",
]
