"""
Audits "name + trailing qualifier" pairs (e.g. zantac / zantac 360,
tagamet / tagamet hb) for label consistency between P (confirmed
positives) and U (the noise pipeline's generated negatives).

A pair matches the pattern iff, after normalization, one name is a strict
prefix of the other AND the split lands on a word boundary (the shorter
name is followed by a space, not merged into a longer word). This is
deliberately stricter than "shares a word" - "super drug" is NOT a prefix
of "super duper drug" (they diverge inside the second word), so pairs like
that are excluded by construction; only true name+trailing-qualifier pairs
match.

P_us.csv already labels this pattern as positive/confusable (zantac /
zantac 360 = 1). This script checks whether U, generated by the same
src/pipeline/noise.py that trains the model, contains any pairs matching
the same pattern - which would be a direct label contradiction, since U
rows are treated as negative during training.

Usage: uv run python scripts/audit_qualifier_pairs.py
"""

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import COL_X1, COL_X2, DataSource, R_CLEAN, P
from src.pipeline.noise import make_noise, normalize

P_US_CSV = P[DataSource.US]
R_US_CLEAN_CSV = R_CLEAN[DataSource.US]


def is_qualifier_pair(a: str, b: str) -> bool:
    """True iff normalize(a) is a strict, word-boundary prefix of
    normalize(b), or vice versa."""
    na, nb = normalize(a), normalize(b)
    if na == nb:
        return False
    short, long_ = (na, nb) if len(na) < len(nb) else (nb, na)
    if not long_.startswith(short):
        return False
    # word boundary: next char after the shared prefix must be a space
    return long_[len(short)] == " "


def find_qualifier_pairs(df: pd.DataFrame) -> pd.DataFrame:
    mask = [is_qualifier_pair(a, b) for a, b in zip(df[COL_X1], df[COL_X2])]
    return df[mask]


def main() -> None:
    p_df = pd.read_csv(P_US_CSV)
    registry_df = pd.read_csv(R_US_CLEAN_CSV)

    print(f"[audit] Loaded P_us.csv: {len(p_df):,} confirmed positive pairs")
    print(f"[audit] Loaded registry: {len(registry_df):,} names")

    p_qual = find_qualifier_pairs(p_df)
    print(
        f"\n[audit] Name+qualifier pairs in P (positive, label=1): "
        f"{len(p_qual):,} / {len(p_df):,}"
    )
    for _, row in p_qual.iterrows():
        print(f"    + {row[COL_X1]!r:35} {row[COL_X2]!r}")

    print("\n[audit] Generating U via the actual noise pipeline (src/pipeline/noise.py, "
          "same SEED as training) ...")
    u_df = make_noise(p_df, registry_df)

    u_qual = find_qualifier_pairs(u_df)
    print(
        f"\n[audit] Name+qualifier pairs in U (negative/unlabeled, label=0): "
        f"{len(u_qual):,} / {len(u_df):,}"
    )
    for _, row in u_qual.iterrows():
        print(f"    - {row[COL_X1]!r:35} {row[COL_X2]!r}  (tier={row['tier']}, sim={row['similarity']})")

    print("\n[audit] === Summary ===")
    print(f"  P qualifier pairs (correctly positive): {len(p_qual):,}")
    print(f"  U qualifier pairs (inconsistently negative): {len(u_qual):,}")
    if len(u_qual):
        frac = len(u_qual) / len(u_df) * 100
        print(
            f"  These {len(u_qual):,} rows are {frac:.4f}% of U but are all cases "
            "where P_us.csv's own convention (name+qualifier => confusable) "
            "says they should be positive, not negative."
        )

    out_path = Path("results/qualifier_pair_audit.csv")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    p_qual = p_qual.assign(source="P", correct_label=1, current_label=1)
    u_qual = u_qual.assign(source="U", correct_label=1, current_label=0)
    combined = pd.concat(
        [
            p_qual[[COL_X1, COL_X2, "source", "current_label", "correct_label"]],
            u_qual[[COL_X1, COL_X2, "source", "current_label", "correct_label"]],
        ],
        ignore_index=True,
    )
    combined.to_csv(out_path, index=False)
    print(f"\n[audit] Wrote full list -> {out_path}")


if __name__ == "__main__":
    main()
