"""AI inference backends for finding confusable drug pairs.

This package provides two backends for AI-assisted drug confusion analysis:
    - local: Runs a model locally on your machine using HuggingFace Transformers.
    - api: Calls a remote API provider (such as DeepSeek) via an OpenAI-compatible client.
"""


def clean_output(text: str, candidates: list[str]) -> list[str]:
    """Filter AI text output to retain only valid names from the candidate list.

    Prevents hallucinated or invented drug names from entering the dataset.

    Args:
        text: Raw text response generated by the AI model.
        candidates: List of valid drug names provided in the prompt.

    Returns:
        List of verified drug names matched case-insensitively without duplicates.

    """
    candidate_set = {c.lower() for c in candidates}
    seen: set[str] = set()
    valid: list[str] = []
    for line in text.strip().split("\n"):
        line = line.strip().lower()
        if line in candidate_set and line not in seen:
            valid.append(line)
            seen.add(line)
    return valid
