algorithm = "editex"
[costs]
same = 1.0
diff = 2.0

[group]
a = [0]
b = [1]
c = [2, 9]
d = [3]
e = [0]
f = [7]
g = [6]
h = [0]
i = [0]
j = [6]
k = [2]
l = [4]
m = [5]
n = [5]
o = [0]
p = [1, 7]
q = [2]
r = [4]
s = [8, 9]
t = [3]
u = [0]
v = [7]
w = [0]
x = [8]
y = [0]
z = [8, 9]